# Generated by Django 4.0.5 on 2022-06-06 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_font_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='child_category',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, limit_choices_to={'font_type': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category'),
        ),
    ]
