# Generated by Django 4.0.5 on 2022-06-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_category_child_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
