# Generated by Django 4.0.5 on 2022-06-07 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_name_remove_category_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category'),
        ),
    ]
