# Generated by Django 4.0.5 on 2022-06-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_branding_shop_alter_product_category_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='branding_shop',
        ),
    ]
