# Generated by Django 4.0.5 on 2022-06-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_branding_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_shop',
        ),
        migrations.AddField(
            model_name='product',
            name='category_shop',
            field=models.ManyToManyField(limit_choices_to={'font_type__lt': 4}, to='product.category'),
        ),
    ]
