# Generated by Django 4.0.5 on 2022-06-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_category_shop_product_category_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(default='tag', related_name='tags', to='product.category'),
        ),
    ]
