# Generated by Django 4.0.5 on 2022-06-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(default={'font_type__lt': 3}, related_name='tags', to='product.category'),
        ),
    ]
