# Generated by Django 4.0.5 on 2022-06-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
